### ISSUE TITLE
JSPの改行位置

### ISSUE THREAD

**Issue by ghost** [soejima-reona/soejima_reona#1]
https://github.com/soejima-reona/soejima_reona/blob/bb5d23533aa68c2b13fff752a76acb0ca4e4ecd8/WebContent/Top.jsp#L50-L51

> <c:if 
の次で改行されているところが気になりますね。
いきなり「test=」って行頭に出てくるのはなんのタグに対応する属性なのかがわかりづらいですね。

**Comment by soejima-reona** [comment]
修正しました！
