### ISSUE TITLE
アカウントの重複チェック

### ISSUE THREAD

**Issue by ghost** [soejima-reona/soejima_reona#3]
https://github.com/soejima-reona/soejima_reona/blob/bb5d23533aa68c2b13fff752a76acb0ca4e4ecd8/src/chapter7/controller/SignUpServlet.java#L108

L83でやってるのでは？
あとメールアドレスの重複チェックはいらないです。

**Comment by ghost** [comment]
https://github.com/soejima-reona/soejima_reona/blob/bb5d23533aa68c2b13fff752a76acb0ca4e4ecd8/src/chapter7/controller/SettingsServlet.java#L141

ここも

**Comment by soejima-reona** [comment]
不要な文だったので消去しました。
