### ISSUE TITLE
ユーザの停止復活に用いると思われるServletのdoGetについて

### ISSUE THREAD

**Issue by ghost** [soejima-reona/soejima_reona#4]
https://github.com/soejima-reona/soejima_reona/blob/bb5d23533aa68c2b13fff752a76acb0ca4e4ecd8/src/chapter7/controller/StoppedServlet.java#L18-L31

このdoGetが実行される状況が見えないのですが、どんな時にこいつが実行されますか？

**Comment by soejima-reona** [comment]
アカウントを停止(復活)するユーザーの特定に必要かと思い実装していましたが、
不要だったので削除しました。
